export const FIRST_NAMES_M = [
  "Agustín",
  "Alejandro",
  "Andrés",
  "Bruno",
  "Carlos",
  "Daniel",
  "Diego",
  "Eduardo",
  "Emilio",
  "Ezequiel",
  "Facundo",
  "Federico",
  "Fernando",
  "Francisco",
  "Gabriel",
  "Gastón",
  "Gonzalo",
  "Guillermo",
  "Hernán",
  "Ignacio",
  "Javier",
  "Joaquín",
  "Jorge",
  "José",
  "Juan",
  "Julián",
  "Leandro",
  "Leonardo",
  "Lorenzo",
  "Lucas",
  "Luis",
  "Marcelo",
  "Martín",
  "Matías",
  "Maximiliano",
  "Miguel",
  "Nicolás",
  "Pablo",
  "Patricio",
  "Pedro",
  "Rafael",
  "Ramón",
  "Ricardo",
  "Roberto",
  "Rodrigo",
  "Santiago",
  "Sebastián",
  "Sergio",
  "Tomás",
  "Valentín",
];

export const FIRST_NAMES_F = [
  "Agustina",
  "Alejandra",
  "Analía",
  "Andrea",
  "Belén",
  "Camila",
  "Carolina",
  "Clara",
  "Claudia",
  "Daniela",
  "Elena",
  "Emilia",
  "Florencia",
  "Gabriela",
  "Inés",
  "Isabel",
  "Josefina",
  "Julia",
  "Laura",
  "Liliana",
  "Luciana",
  "Lucía",
  "Luisa",
  "Magdalena",
  "María",
  "Mariana",
  "Martina",
  "Mercedes",
  "Micaela",
  "Mónica",
  "Natalia",
  "Natasha",
  "Noemí",
  "Patricia",
  "Paula",
  "Romina",
  "Rosa",
  "Sabrina",
  "Silvia",
  "Sofía",
  "Soledad",
  "Susana",
  "Tamara",
  "Valentina",
  "Valeria",
  "Vanesa",
  "Verónica",
  "Victoria",
  "Virginia",
  "Ximena",
];

export const LAST_NAMES = [
  "Acosta",
  "Aguirre",
  "Álvarez",
  "Arias",
  "Benítez",
  "Blanco",
  "Cabrera",
  "Cardozo",
  "Castro",
  "Córdoba",
  "Cruz",
  "Díaz",
  "Domínguez",
  "Escobar",
  "Espinoza",
  "Fernández",
  "Ferreira",
  "Flores",
  "Frías",
  "García",
  "Gómez",
  "González",
  "Gutiérrez",
  "Herrera",
  "Ibáñez",
  "Jiménez",
  "Juárez",
  "López",
  "Luna",
  "Martínez",
  "Medina",
  "Mendoza",
  "Molina",
  "Morales",
  "Moreno",
  "Moyano",
  "Muñoz",
  "Navarro",
  "Núñez",
  "Ojeda",
  "Olivares",
  "Ortega",
  "Ortiz",
  "Páez",
  "Peralta",
  "Pérez",
  "Quiroga",
  "Ramírez",
  "Ramos",
  "Reyes",
  "Ríos",
  "Rivas",
  "Rivera",
  "Rodríguez",
  "Rojas",
  "Romano",
  "Romero",
  "Ruiz",
  "Salazar",
  "Salinas",
  "Sánchez",
  "Silva",
  "Soria",
  "Soto",
  "Suárez",
  "Torres",
  "Vargas",
  "Vega",
  "Vera",
  "Villalba",
  "Villalobos",
  "Villanueva",
];

export const EMAIL_DOMAINS = [
  "gmail.com",
  "hotmail.com",
  "yahoo.com",
  "outlook.com",
  "icloud.com",
  "protonmail.com",
  "live.com",
  "yahoo.com.ar",
  "hotmail.com.ar",
  "fibertel.com.ar",
  "speedy.com.ar",
];

export const AR_STREETS = [
  "Av. Corrientes",
  "Av. Rivadavia",
  "Av. Santa Fe",
  "Av. Callao",
  "Av. Córdoba",
  "Florida",
  "Lavalle",
  "Av. de Mayo",
  "Reconquista",
  "Sarmiento",
  "Suipacha",
  "Av. 9 de Julio",
  "Av. Libertador",
  "Av. Cabildo",
  "Av. Las Heras",
  "Av. Pueyrredón",
  "Av. Entre Ríos",
  "Av. San Juan",
  "Av. Independencia",
  "Bartolomé Mitre",
  "Tucumán",
  "Viamonte",
  "Paraguay",
  "Marcelo T. de Alvear",
  "Charcas",
  "Av. Scalabrini Ortiz",
  "Av. Medrano",
  "Av. Díaz Vélez",
];

export const AR_CITIES: { city: string; province: string; cp: string }[] = [
  { city: "Buenos Aires", province: "CABA", cp: "1000" },
  { city: "Córdoba", province: "Córdoba", cp: "5000" },
  { city: "Rosario", province: "Santa Fe", cp: "2000" },
  { city: "Mendoza", province: "Mendoza", cp: "5500" },
  { city: "La Plata", province: "Buenos Aires", cp: "1900" },
  { city: "San Miguel de Tucumán", province: "Tucumán", cp: "4000" },
  { city: "Mar del Plata", province: "Buenos Aires", cp: "7600" },
  { city: "Salta", province: "Salta", cp: "4400" },
  { city: "Santa Fe", province: "Santa Fe", cp: "3000" },
  { city: "San Juan", province: "San Juan", cp: "5400" },
  { city: "Resistencia", province: "Chaco", cp: "3500" },
  { city: "Neuquén", province: "Neuquén", cp: "8300" },
  { city: "Formosa", province: "Formosa", cp: "3600" },
  { city: "San Salvador de Jujuy", province: "Jujuy", cp: "4600" },
  { city: "Bahía Blanca", province: "Buenos Aires", cp: "8000" },
];

export const CL_STREETS = [
  "Av. Providencia",
  "Av. Apoquindo",
  "Moneda",
  "Agustinas",
  "Huérfanos",
  "Compañía de Jesús",
  "Av. Libertador Bernardo O'Higgins",
  "Av. Santa Rosa",
  "Av. Irarrázaval",
  "Av. Pedro de Valdivia",
  "Av. Manuel Montt",
  "Lord Cochrane",
  "Monjitas",
  "Catedral",
  "San Antonio",
  "Nueva York",
  "Bandera",
  "Estado",
  "Teatinos",
  "Mac-Iver",
  "Merced",
  "Av. Francisco Bilbao",
];

export const CL_CITIES: { city: string; region: string }[] = [
  { city: "Santiago", region: "Región Metropolitana" },
  { city: "Valparaíso", region: "Valparaíso" },
  { city: "Concepción", region: "Biobío" },
  { city: "Antofagasta", region: "Antofagasta" },
  { city: "Viña del Mar", region: "Valparaíso" },
  { city: "Rancagua", region: "O'Higgins" },
  { city: "Temuco", region: "La Araucanía" },
  { city: "Iquique", region: "Tarapacá" },
  { city: "Puerto Montt", region: "Los Lagos" },
  { city: "Arica", region: "Arica y Parinacota" },
];

export const AR_AREA_CODES = [
  "351",
  "341",
  "261",
  "223",
  "299",
  "387",
  "376",
  "380",
  "362",
  "370",
];

export const USER_AGENTS = [
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15",
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0",
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Mobile/15E148 Safari/604.1",
  "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0",
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 OPR/116.0.0.0",
  "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0",
];
